# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\x12\x0c\x66ile_service\"\x12\n\x10ListFilesRequest\"&\n\x11ListFilesResponse\x12\x11\n\tfilenames\x18\x01 \x03(\t\"%\n\x11\x46ileExistsRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"$\n\x12\x46ileExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\xb0\x01\n\x0b\x46ileService\x12N\n\tListFiles\x12\x1e.file_service.ListFilesRequest\x1a\x1f.file_service.ListFilesResponse\"\x00\x12Q\n\nFileExists\x12\x1f.file_service.FileExistsRequest\x1a .file_service.FileExistsResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LISTFILESREQUEST._serialized_start=36
  _LISTFILESREQUEST._serialized_end=54
  _LISTFILESRESPONSE._serialized_start=56
  _LISTFILESRESPONSE._serialized_end=94
  _FILEEXISTSREQUEST._serialized_start=96
  _FILEEXISTSREQUEST._serialized_end=133
  _FILEEXISTSRESPONSE._serialized_start=135
  _FILEEXISTSRESPONSE._serialized_end=171
  _FILESERVICE._serialized_start=174
  _FILESERVICE._serialized_end=350
# @@protoc_insertion_point(module_scope)
