# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egreeting.proto\"\x1f\n\x0b\x43lientInput\x12\x10\n\x08greeting\x18\x01 \x01(\t\"\x1f\n\x0cServerOutput\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\x10ListFilesRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"&\n\x11ListFilesResponse\x12\x11\n\tfilenames\x18\x01 \x03(\t\"%\n\x11\x46ileExistsRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"$\n\x12\x46ileExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32|\n\x0b\x46ileService\x12\x34\n\tListFiles\x12\x11.ListFilesRequest\x1a\x12.ListFilesResponse\"\x00\x12\x37\n\nFileExists\x12\x12.FileExistsRequest\x1a\x13.FileExistsResponse\"\x00\x32\x31\n\x07Greeter\x12&\n\x05greet\x12\x0c.ClientInput\x1a\r.ServerOutput\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeting_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTINPUT._serialized_start=18
  _CLIENTINPUT._serialized_end=49
  _SERVEROUTPUT._serialized_start=51
  _SERVEROUTPUT._serialized_end=82
  _LISTFILESREQUEST._serialized_start=84
  _LISTFILESREQUEST._serialized_end=120
  _LISTFILESRESPONSE._serialized_start=122
  _LISTFILESRESPONSE._serialized_end=160
  _FILEEXISTSREQUEST._serialized_start=162
  _FILEEXISTSREQUEST._serialized_end=199
  _FILEEXISTSRESPONSE._serialized_start=201
  _FILEEXISTSRESPONSE._serialized_end=237
  _FILESERVICE._serialized_start=239
  _FILESERVICE._serialized_end=363
  _GREETER._serialized_start=365
  _GREETER._serialized_end=414
# @@protoc_insertion_point(module_scope)
